-- Base de datos para el módulo de inventario - MYSQL
-- tablas existentes: colaboradores, productos
CREATE TABLE AUDITORIA_REGULARIZACION(
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA_ACTUALIZACION TIMESTAMP,
DATOS_CAMBIADOS JSON
);

CREATE TABLE IF NOT EXISTS TIENDAS(
ID INT PRIMARY KEY AUTO_INCREMENT
);
INSERT INTO TIENDAS() VALUES("");

CREATE TABLE IF NOT EXISTS ALMACENES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
CANTIDAD INT DEFAULT 0,
ESTADO CHAR (1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS IVENTARIO(
ID INT PRIMARY KEY AUTO_INCREMENT,
NUMERO VARCHAR(20) UNIQUE NOT NULL,
AREA VARCHAR(20), -- lo unimos a la tabla de áreas?
AUTORIZADO_POR INT REFERENCES colaboradores(ID_PERSONA),
ESTADO CHAR(1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS IVENTARIOS_CONTEO(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_INVENTARIO  INT REFERENCES INVENTARIO(ID),
ID_ALMACEN INT REFERENCES ALMACENES(ID),
REGISTRADO_POR INT REFERENCES colaboradores(ID_PERSONA),
FECHA_REGISTRO TIMESTAMP,
ESTADO CHAR(1) DEFAULT 1
);
